# Generated by Django 4.1.7 on 2023-04-14 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='design',
            fields=[
                ('node_type', models.IntegerField()),
                ('created_user', models.CharField(max_length=255)),
                ('globalid', models.CharField(max_length=50)),
                ('muuid', models.CharField(max_length=50)),
                ('eversource_id', models.CharField(max_length=255)),
                ('mav_site', models.CharField(max_length=255)),
                ('node_config', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('inventory_status', models.IntegerField()),
                ('gis_id', models.CharField(max_length=255)),
                ('symbol_id', models.CharField(max_length=255)),
                ('last_edited_user', models.CharField(max_length=255)),
                ('last_edited_date', models.DateField(blank=True, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('comments', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=None, null=True)),
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'map_A_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issue', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'map_A_marker',
                'managed': False,
            },
        ),
    ]
